

spring.datasource.url=jdbc:mysql://localhost:3306/interview_tracker
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
youtube.api.key=AIzaSyAfzTeKX_rPpf3A1ffhMSKd4PjfMd34I4o
youtube.api-key=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
groq.api.key=${GROQ_API_KEY}
